name: Run sendnews.py daily

on:
  schedule:
    - cron: "0 9 * * *"   # runs daily at 09:00 UTC
  workflow_dispatch:       # allows manual run from Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python AINews/sendnews.py
